### ISSUE TITLE
알고리즘 설계

### ISSUE THREAD

**Issue by songhune** [songhune/MemNet#2]
1. 메모리<SS 일때,
   inference(여기서는 단순히 softmax, ss와 q)를 해서 가장 연관성이 낮은 벡터를 제외한 나머지 벡터를 반환한다.
  이렇게 해서 최종적으로는 메모리 사이즈에 맞춘다.
2. 이과정을 tf가 아닌 np 내에서 한다.
3. word correlation이 알파벳 순으로만 되어있는 한계 포착.
    cosine similarity 공부(td-idf)

**Comment by rizejin** [comment]
좀 전에 논의한 바와 같이 교체 조작이 여러 곳에서 발생할 수 있는데 
우선 텐서플로우 세션 런하기 전에 메모리 사이즈에 맞추면 된다.

교체 기법이 대략 세션 런 전,후 2개 종류로 나눌 수 있다. 
1. 세션 런 전: 
   이 경우엔 원 코드의 inference 로직을 못으니 넌판이로 교체 로직을 구현해야 한다.
2. 세전 런 후:
   이 경우엔 inference 실행 결과를 보고 교체 대상을 선정한다.

**Comment by songhune** [comment]
교수님, 수정했습니다.
single.py로 테스트해보시면 될 것 같구요, task 2로 preset되어 있습니다.
data_util.py에서 제일 많이 변경점이 있는데, 이 부분에 대해 의논하고 싶습니다.
결과적으로는 성능이 떨어진거 같은데, 코딩 실수인지, 알고리즘상에 문제가 있는지 알아봐야 할 것 같습니다.

**Comment by rizejin** [comment]
코드 확인해봤다. 코딩 실수는 없는것 같고 잘 했다.
소프트맥스로 스토리 매트릭스과 질의 백터간의 관련성을 찾는게 타당하지 않아보인다. 그래서 결과 안 좋은거구. 관련성 찾는 알고리즘으로 대체하면 의도대로 작동할 것 같다.

**Comment by rizejin** [comment]
관련성 계산 관련 여러 방법을 생각해 봤는데 일단 나열해보고 만나서 논의해보자.
1. 씨맨틱 정보를 가진 word embedding (e.g. w2v) 을 사용하여 백터를 만들면 cosine distance를 계산하여 관련성을 찾는 것.
2. 전처리도 고려할마한지.... 전처리 한다면 stopword removing, stemming 등을 고려할수 있겠다.
3. 지금 보면 zero padding 엄청 많이 들어갔는데 그는 일정 길이를 유지할려고하는거고 꼭 그렇게 해야하는지 의문이다. 예를 들면 가변의 문장길이, 가변의 메모리 길이의 input을 수용할수 있는 구조를 만들수 있으면 input이 보다 컴팩트하고 공간 낭비를 방지하겠지.
4. 문장 매트릭스과 질의 백터의 유사도, 관련성을 찾는 기존 방법이 있겠지 이에대해 기존 연구 서베이 필요로 해 보인다. 잘 몰라서 하는 말일 수 있고 clustering 기법으로 관련 문장을 찾을 수 있을것 같다. 
     예를 들면 처음에는 문장셋 중 질의한 가장 가까운 한 문장(s1) 찾고, 두번째 라운드에서는 문장셋 중 질의, s1 과 제일 가까운 한 문장 (s2) 을 찾는다. 이 과정을 반복하면 관련성 높은 여려 문장을 찾을 수 있을것 같다. 
5. 너무 많이 전처리하면 (stemming .. )  엔드 투 엔드의 장점을 약화시키는 단점일 있을것 같다. raw data만 넣겠다는 입장에서 보면 우리가 지금 하는 방법들을 오히려 문장수를 적게 nn에 보내주는것 같다. 원래도 트레이닝 데이터가 그렇게 많은것도 아닌데 양을 줄여서 넣는것도 성능 저하 시키는 원인이 되는것 같다. 그래서 data augmentation 방법을 사용하는게 좋지 않을까. 예를 들면 스토리를 메모리 길이에 맞춰서 여려개로 쪼개는 것. 물론 substory마다 supporting sentence들이 꼭 있어야겠지.

그래도 네가 틀을 얼마정도 구현 다했으니 핵심 아이디어에만 집중하면 되겠다. 
수고했다.

**Comment by songhune** [comment]
1 - 보류
2 - 보류
3 - 1. no zero padding
4 - 옛날방식, 머신러닝이 아닌 알고리즘을 제시하는 이슈

~~restricted resource라는 것을 이루기 위해서라도 기존의 zero padding을 줄여볼 여지는 있다.~~

**Comment by songhune** [comment]
1. Data Augmentation
2. FIFO vs LPU

**Comment by rizejin** [comment]
Data Augmentation:
원 코드보면 supporting sentence만 뽑는 기능이 있고 
그럼 전체 스토리를 슈퍼셋이라고 생각하고 여러 sub스토리를 만들수 있잖아 
supporting sentence들이 꼭 들어 있도록하는것만 해주면 트레이닝 셋을 증가할 수 있지.

일단 1000개의 트레이닝 데이터를 4000개로 확장하여 실험해보면 좋겠다.

**Comment by songhune** [comment]
_원 코드보면 supporting sentence만 뽑는 기능이 있고_ 
`def load_task(data_dir, task_id, only_supporting=False):`
이 부분을 True로 바꿨을 때 데이터를 확인해보겠습니다.

_**그럼** 전체 스토리를 슈퍼셋이라고 생각하고 **여러 sub스토리를 만들수 있잖아**_ 
여러 substory를 만든다는 것이 무슨 말씀이신지 잘 모르겠습니다.

**Comment by rizejin** [comment]
정확한 용어는 subset 스토리고 예를 들면 1~7번호를 가진 스토리가 있다고 하고 그중 3,5가 supporting sentence이고 그러면 1,2,3,5,7이 한 subset 스토리가 될 수 있지. 이런 subset스토리가 총 (7-2)!개 있겠지
다 뽑을 필요는 없고 임의로 3,4개 뽑아서 트레이닝 셋을 확장하면 되
