### ISSUE TITLE
# locations between supporting sentence and query

### ISSUE THREAD

**Issue by songhune** [songhune/MemNet#5]
@rizejin 
교수님꼐서 몇몇 케이스를 가지고 실험하셨다곤 했는데
실제로 SS의 위치와 Query간의 거리상의 거리를 측정하고
몇몇 시각화 기반 데이터 수집(이를테면 tf-idf수치 등)을 해보고 싶은데
유효성 검토를 별도로 시각화할 수 있는 코드를 작성하는건 어떨까요?

**Comment by rizejin** [comment]
fifo, lilo, lpu 성능을 얘기하는거야?
그걸 시각화할 필요는 없을것 같애

**Comment by songhune** [comment]
LPU의 성능이 낮은 이유로 두가지를 교수님이 언급하셨습니다.
1. argmin(Sofmax(dot(story, query)))가 query의 features를 잘 반영하지 못한다.
2. 전반적으로 long-term dependency를 가지는 문장에서의 SS가 query 근처에 집중되어 있다.

1번은 import word2vec이나 cosine distance등 전통적인 방법 등을 import함으로서 해결(보류)한다고 본다면, 2번 이슈에 대해서는 '그냥 그렇게 보인다'가 아니라 실제로 SS의 위치가 paragraph의 후반부에 위치하는지 여부를 검증할 필요가 있을 것 같습니다.

**Comment by songhune** [comment]
@rizejin 이거로 embedding을 써보는 것도 방법이 될 수 있지 않을까요
https://github.com/facebookresearch/fastText
